/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Theses */
        get: operations["list_theses_theses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theses/{thesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thesis */
        get: operations["get_thesis_theses__thesis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theses/{thesis_id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Call
         * @description Recompute the CallCard live at ``asof`` — a READ-ONLY path. The signal stream is re-derived
         *     from the bitemporal facts (no persisted firing layer), so a given ``asof`` is deterministic and a
         *     refetch / as-of-slider scrub / poll writes nothing. The accountability ``calls`` log is written
         *     by the batch ``pipeline.run`` (the official call of record), never by this GET.
         */
        get: operations["get_call_theses__thesis_id__call_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Archetype
         * @description A basket member's role in expressing the thesis.
         * @enum {string}
         */
        Archetype: "leader" | "high_beta" | "lotto" | "shovel";
        /** BasketMember */
        BasketMember: {
            /** Ticker */
            ticker: string;
            /** Role */
            role: string;
            archetype: components["schemas"]["Archetype"];
            /** Security Id */
            security_id?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /**
         * CallCardResponse
         * @description The CallCard as served — the domain card plus resolved provenance URLs.
         */
        CallCardResponse: {
            /**
             * Thesis Id
             * Format: uuid
             */
            thesis_id: string;
            /**
             * Asof
             * Format: date
             */
            asof: string;
            state: components["schemas"]["State"];
            verdict: components["schemas"]["Verdict"];
            conviction_grade?: components["schemas"]["Grade"] | null;
            entry_grade?: components["schemas"]["Grade"] | null;
            /** Armed Security Id */
            armed_security_id?: string | null;
            /** Expression */
            expression: string;
            /** Exit By */
            exit_by?: string | null;
            /** Arm Until */
            arm_until?: string | null;
            /**
             * Catalyst Surface
             * @default []
             */
            catalyst_surface: components["schemas"]["Catalyst"][];
            /** Confidence */
            confidence: number;
            key_conviction: components["schemas"]["KeyState"];
            key_confirmation: components["schemas"]["KeyState"];
            /**
             * Triggers Fired
             * @default []
             */
            triggers_fired: components["schemas"]["TriggerRefOut"][];
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Counter Case
             * @default
             */
            counter_case: string;
            /** Safe Sleeve */
            safe_sleeve?: string | null;
        };
        /** Catalyst */
        Catalyst: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Kind */
            kind?: string | null;
            /** When Date */
            when_date?: string | null;
            /** When Label */
            when_label?: string | null;
        };
        /**
         * Evidence
         * @description Immutable reference to a filing / data point.
         */
        Evidence: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Ref */
            ref: string;
            /** Date Label */
            date_label?: string | null;
        };
        /**
         * Grade
         * @enum {string}
         */
        Grade: "flip" | "core";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeyState
         * @description One of the two keys (Conviction / Confirmation) rendered on the call card.
         */
        KeyState: {
            /** Turned */
            turned: boolean;
            /** Label */
            label: string;
            /** Detail */
            detail?: string | null;
        };
        /** KillCriterion */
        KillCriterion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * Kind
         * @description What produced the signal (extensible).
         * @enum {string}
         */
        Kind: "insider" | "technical_breakout" | "laggard" | "squeeze" | "etf_launch" | "etf_flow" | "dilution_risk";
        /**
         * Position
         * @description Populated once the operator logs a fill — its presence drives the Managing state.
         */
        Position: {
            /** Entry Price */
            entry_price?: number | null;
            /** Current Price */
            current_price?: number | null;
            /** Opened On */
            opened_on?: string | null;
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /** Source */
            source: string;
            /** Ref */
            ref: string;
            /** Url */
            url?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
        };
        /**
         * State
         * @description Thesis lifecycle (a loop, not a ratchet).
         * @enum {string}
         */
        State: "incubating" | "warming" | "armed" | "managing";
        /**
         * ThesisDetail
         * @description The full thesis for the Cockpit — a wire model (no tenant_id) so generated FE types never bind
         *     to the domain Thesis. Sub-objects reuse the domain value types (no transform needed, like the
         *     catalyst surface on CallCardResponse).
         */
        ThesisDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Name */
            name: string;
            /** Narrative */
            narrative: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket
             * @default []
             */
            basket: components["schemas"]["BasketMember"][];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Catalysts
             * @default []
             */
            catalysts: components["schemas"]["Catalyst"][];
            /**
             * Kill Criteria
             * @default []
             */
            kill_criteria: components["schemas"]["KillCriterion"][];
            position?: components["schemas"]["Position"] | null;
        };
        /**
         * ThesisSummary
         * @description Lightweight list item for the Board (the full thesis comes from GET /theses/{id}).
         */
        ThesisSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker?: string | null;
            /** Narrative */
            narrative: string;
        };
        /** TriggerRefOut */
        TriggerRefOut: {
            /** Label */
            label: string;
            kind: components["schemas"]["Kind"];
            grade?: components["schemas"]["Grade"] | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["ProvenanceOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "watching" | "not_yet" | "flip_only" | "starter_entry" | "core_entry" | "managing";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_theses_theses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisSummary"][];
                };
            };
        };
    };
    get_thesis_theses__thesis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_theses__thesis_id__call_get: {
        parameters: {
            query: {
                /** @description as-of date; the call uses no data knowable after it */
                asof: string;
            };
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
