/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Theses */
        get: operations["list_theses_theses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theses/{thesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thesis */
        get: operations["get_thesis_theses__thesis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theses/{thesis_id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Call
         * @description Recompute the CallCard live at ``asof`` — a READ-ONLY path. The signal stream is re-derived
         *     from the bitemporal facts (no persisted firing layer), so a given ``asof`` is deterministic and a
         *     refetch / as-of-slider scrub / poll writes nothing. The accountability ``calls`` log is written
         *     by the batch ``pipeline.run`` (the official call of record), never by this GET.
         */
        get: operations["get_call_theses__thesis_id__call_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/scored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scored
         * @description Re-derive the per-name Workbench scores live at ``asof`` — a READ-ONLY path (Option B; nothing
         *     persists). Mirrors the call endpoint: load the thesis (404 + its tenant), thread ``thesis.tenant_id``
         *     into every scoring fact read so a production thesis scores off production's facts.
         */
        get: operations["get_scored_workbench_theses__thesis_id__scored_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Securities
         * @description Search the current tenant's security master for names to PLACE into a basket (the authoring
         *     typeahead, Slice 4b). A DISCOVERY NET (INVARIANT #2): exact master rows for the operator to pick from
         *     — never a fuzzy decision, never an ingest (no ``allow_live``). No match -> ``[]``; the operator's pick
         *     carries the exact ``security_id``. Tenant from the deployment resolver (which universe to author in).
         */
        get: operations["search_securities_workbench_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/securities/{security_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extract Scoring Facts
         * @description Auto-EXTRACT candidate scoring facts for a security from its latest SEC 10-Q/10-K (Slice hybrid-1) —
         *     the three-tier hybrid: AUTO pre-fills the clean facts, FLAG carries the raw value + a detected risk + the
         *     located passage (the operator ratifies the composition), HUMAN (purity) is LOCATED only and never
         *     auto-valued. An EXPLICIT operator action (cache-first, live SEC), never fired on a render. The extractor
         *     never DECIDES — the operator confirms (hybrid-2). Requires ``ALPHADECK_USER_AGENT`` (SEC etiquette).
         */
        get: operations["extract_scoring_facts_workbench_securities__security_id__extract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/facts/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Flag Candidate
         * @description Draft a plain-English explanation of a FLAG candidate, grounded in its located passage — the one LLM
         *     seam (M4b). A DISPLAY aid shown ALONGSIDE the raw passage; it NEVER becomes a fact.
         *
         *     Note what is absent: no ``get_conn``, no tenant, no write. The explanation rides a separate rail that
         *     dead-ends at the screen — the ratified number can only ever come from the operator's typed field on
         *     ``/facts`` (INVARIANT #3). The prompt asks the model not to state the final value; this missing
         *     connection is what guarantees it can't become one.
         *
         *     Fail-open by contract: any LLM trouble (no ``ANTHROPIC_API_KEY``, timeout, SDK error, or the model
         *     declining to ground it) returns 200 with ``{explanation: "", grounded: false}`` — NEVER a 5xx. The facts
         *     panel renders identically to today. (FLAG-only: a non-FLAG candidate returns the same empty signal.)
         */
        post: operations["explain_flag_candidate_workbench_facts_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote
         * @description Promote a structured thesis to the Board (Incubating) — the app's FIRST mutation. Create (``id``
         *     null) or update (``id`` set); the value-chain structure (segments + placements + authorship) persists
         *     via ``thesis_repo.upsert`` (the existing operational save path). The tenant comes from the deployment
         *     resolver, NOT the body. Scores are never sent and never persist — they re-derive on read.
         */
        post: operations["promote_workbench_theses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ratify Fact
         * @description Ratify an extracted candidate -> write the scoring fact (hybrid-2a) — the app's first fact-WRITE. The
         *     operator confirms/edits a candidate (AUTO as-is, FLAG the composition, HUMAN purity the value); this
         *     persists it via the existing ``ingest_*`` so the meter re-derives on the next scored read.
         *
         *     WRITE-SIDE TENANT DISCIPLINE: the security must be in the CURRENT tenant's master (fail-closed) — the
         *     tenant is the deployment resolver's, but the ``security_id`` is caller-supplied, so a foreign/unknown id
         *     must not write a junk fact. ``source`` is preserved (the candidate's basis, e.g. ``10-k-segment``);
         *     ``ratified_by`` is stamped "operator"; the fact is append-only (a re-ratify is a new row, latest-wins).
         */
        post: operations["ratify_fact_workbench_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Archetype
         * @description A basket member's role in expressing the thesis.
         * @enum {string}
         */
        Archetype: "leader" | "high_beta" | "lotto" | "shovel" | "adjacent" | "fund";
        /**
         * Authorship
         * @description Who placed a basket member in its value-chain segment (the Workbench authorship seam).
         *
         *     The MVP writes only the operator values; ``SYSTEM_DRAFTED`` is present now so the seam already
         *     supports the bounded LLM drafter (the next slice) without a later schema change.
         * @enum {string}
         */
        Authorship: "system_drafted" | "operator_set" | "operator_edited";
        /** BasketMember */
        BasketMember: {
            /** Ticker */
            ticker: string;
            /** Role */
            role: string;
            archetype: components["schemas"]["Archetype"];
            /** Security Id */
            security_id?: string | null;
            /** Detail */
            detail?: string | null;
            /** Segment */
            segment?: string | null;
            /** @default operator_set */
            authored_by: components["schemas"]["Authorship"];
        };
        /**
         * CallCardResponse
         * @description The CallCard as served — the domain card plus resolved provenance URLs.
         */
        CallCardResponse: {
            /**
             * Thesis Id
             * Format: uuid
             */
            thesis_id: string;
            /**
             * Asof
             * Format: date
             */
            asof: string;
            state: components["schemas"]["State"];
            verdict: components["schemas"]["Verdict"];
            conviction_grade?: components["schemas"]["Grade"] | null;
            confirmation_grade?: components["schemas"]["Grade"] | null;
            entry_grade?: components["schemas"]["Grade"] | null;
            /** Armed Security Id */
            armed_security_id?: string | null;
            /** Expression */
            expression: string;
            /** Exit By */
            exit_by?: string | null;
            /** Arm Until */
            arm_until?: string | null;
            /**
             * Catalyst Surface
             * @default []
             */
            catalyst_surface: components["schemas"]["Catalyst"][];
            /** Confidence */
            confidence?: number | null;
            key_conviction: components["schemas"]["KeyState"];
            key_confirmation: components["schemas"]["KeyState"];
            /**
             * Triggers Fired
             * @default []
             */
            triggers_fired: components["schemas"]["TriggerRefOut"][];
            /**
             * Risk Signals
             * @default []
             */
            risk_signals: components["schemas"]["TriggerRefOut"][];
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Counter Case
             * @default
             */
            counter_case: string;
            /** Safe Sleeve */
            safe_sleeve?: string | null;
            /**
             * Armed Members
             * @default []
             */
            armed_members: components["schemas"]["MemberCallOut"][];
            /**
             * Watch Members
             * @default []
             */
            watch_members: components["schemas"]["MemberCallOut"][];
        };
        /** Catalyst */
        Catalyst: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Kind */
            kind?: string | null;
            /** When Date */
            when_date?: string | null;
            /** When Label */
            when_label?: string | null;
        };
        /**
         * Evidence
         * @description Immutable reference to a filing / data point.
         */
        Evidence: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Ref */
            ref: string;
            /** Date Label */
            date_label?: string | null;
        };
        /**
         * ExtractedFact
         * @description One candidate scoring fact for a security, with its tier, raw value(s), located evidence, and flags.
         *     The shape mirrors the three ``ingest_*`` writers: shares -> ``value``; cash_burn -> ``cash_usd`` +
         *     ``quarterly_burn_usd``; revenue_mix (purity) -> no value (HUMAN).
         */
        ExtractedFact: {
            /** Fact Type */
            fact_type: string;
            tier: components["schemas"]["Tier"];
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Value */
            value?: number | null;
            /** Cash Usd */
            cash_usd?: number | null;
            /** Quarterly Burn Usd */
            quarterly_burn_usd?: number | null;
            /** Flags */
            flags?: string[];
            /** Located Passages */
            located_passages?: components["schemas"]["LocatedPassage"][];
        };
        /**
         * FlagExplanationOut
         * @description The model-drafted, plain-English explanation of a FLAG candidate, shown ALONGSIDE the raw passage.
         *
         *     Deliberately carries NO value field: it is display-only and never rides the ratify rail (the ratified
         *     number comes solely from the operator's typed field on ``RatifyFactRequest``). ``grounded=False`` (with an
         *     empty ``explanation``) is the honest no-explanation / fail-open signal — the UI shows the raw passage and
         *     manual ratify exactly as today. (INVARIANT #3.)
         */
        FlagExplanationOut: {
            /** Explanation */
            explanation: string;
            /** Grounded */
            grounded: boolean;
        };
        /**
         * Grade
         * @enum {string}
         */
        Grade: "flip" | "core";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeyState
         * @description One of the two keys (Conviction / Confirmation) rendered on the call card.
         */
        KeyState: {
            /** Turned */
            turned: boolean;
            /** Label */
            label: string;
            /** Detail */
            detail?: string | null;
        };
        /** KillCriterion */
        KillCriterion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * Kind
         * @description What produced the signal (extensible).
         * @enum {string}
         */
        Kind: "insider" | "catalyst" | "theme_conviction" | "technical_breakout" | "laggard" | "squeeze" | "etf_launch" | "etf_flow" | "dilution_risk";
        /**
         * LocatedPassage
         * @description A deterministically-retrieved passage that backs a fact — the evidence put in front of the operator
         *     (or, later, S5). Retrieval only: a keyword/section match, never a model's reading.
         */
        LocatedPassage: {
            /** Kind */
            kind: string;
            /** Source Ref */
            source_ref: string;
            /** Anchor */
            anchor: string;
            /** Excerpt */
            excerpt: string;
        };
        /**
         * MemberCallOut
         * @description One basket member's call in the per-member ranked menu (M5 Part A). `armed_members` is ranked
         *     (the headline is [0]); `watch_members` are confirmation-only ("moving, no conviction yet").
         */
        MemberCallOut: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker?: string | null;
            verdict?: components["schemas"]["Verdict"] | null;
            conviction_grade?: components["schemas"]["Grade"] | null;
            confirmation_grade?: components["schemas"]["Grade"] | null;
            entry_grade?: components["schemas"]["Grade"] | null;
            /** Confidence */
            confidence?: number | null;
            /** Exit By */
            exit_by?: string | null;
            /** Arm Until */
            arm_until?: string | null;
            /**
             * Lapsing
             * @default false
             */
            lapsing: boolean;
            /**
             * Theme Armed
             * @default false
             */
            theme_armed: boolean;
            /**
             * Triggers
             * @default []
             */
            triggers: components["schemas"]["TriggerRefOut"][];
        };
        /**
         * Position
         * @description Populated once the operator logs a fill — its presence drives the Managing state.
         */
        Position: {
            /** Entry Price */
            entry_price?: number | null;
            /** Current Price */
            current_price?: number | null;
            /** Opened On */
            opened_on?: string | null;
        };
        /**
         * PromoteThesisRequest
         * @description The promote/update payload — a thesis-with-chain. The router builds a domain Thesis (the
         *     segment-consistency validator runs) under the CURRENT tenant (the resolver, not the body), then upserts
         *     it (create when `id` is null, update otherwise). Scores are NOT sent — they re-derive on read.
         *     `authored_by` is STAMPED server-side (the human path authors `operator_set`), not taken from the body.
         */
        PromoteThesisRequest: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Narrative */
            narrative: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket
             * @default []
             */
            basket: components["schemas"]["BasketMember"][];
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["Segment"][];
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /** Source */
            source: string;
            /** Ref */
            ref: string;
            /** Url */
            url?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
        };
        /** RatifiedFactOut */
        RatifiedFactOut: {
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Fact Type */
            fact_type: string;
        };
        /** RatifyCashBurn */
        RatifyCashBurn: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            fact_type: "cash_burn";
            /** Cash Usd */
            cash_usd: number;
            /** Quarterly Burn Usd */
            quarterly_burn_usd: number;
        };
        /** RatifyRevenueMix */
        RatifyRevenueMix: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            fact_type: "revenue_mix";
            /** Segment Label */
            segment_label: string;
            /** Mix Pct */
            mix_pct: number;
        };
        /** RatifyShares */
        RatifyShares: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            fact_type: "shares_outstanding";
            /** Shares */
            shares: number;
        };
        /**
         * ScoredFigureOut
         * @description One meter/figure on the wire: the 0-4 pip (null = "—"/no data), the raw value, and the provenance
         *     chips ("behind the scores"). market_cap carries `value` only (pips null — a figure, not a meter).
         */
        ScoredFigureOut: {
            /** Pips */
            pips?: number | null;
            /** Value */
            value?: number | null;
            /**
             * Provenance
             * @default []
             */
            provenance: components["schemas"]["ProvenanceOut"][];
        };
        /**
         * ScoredMemberOut
         * @description A basket member scored for the Workbench — the four meters + the market-cap figure + the fit label.
         */
        ScoredMemberOut: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker?: string | null;
            archetype: components["schemas"]["Archetype"];
            /** Segment */
            segment?: string | null;
            purity: components["schemas"]["ScoredFigureOut"];
            runway: components["schemas"]["ScoredFigureOut"];
            catalysts: components["schemas"]["ScoredFigureOut"];
            dilution: components["schemas"]["ScoredFigureOut"];
            market_cap: components["schemas"]["ScoredFigureOut"];
            /** Fit */
            fit: string;
        };
        /**
         * SecurityMatchOut
         * @description A security-master match for the Workbench's add-a-name typeahead (Slice 4b). The operator picks the
         *     exact row; its ``security_id`` is then placed into the basket. A discovery net over the EXISTING
         *     per-tenant master (INVARIANT #2) — every match is a real member, nothing is ingested or guessed.
         */
        SecurityMatchOut: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Cik */
            cik?: string | null;
        };
        /**
         * Segment
         * @description A link in the thesis's value chain (the Workbench decomposition) — STRUCTURE, not a score.
         *
         *     The per-segment candidate count is DERIVED on read (``len`` of members in the link), never stored.
         */
        Segment: {
            /** Label */
            label: string;
            /** Descriptor */
            descriptor?: string | null;
        };
        /**
         * State
         * @description Thesis lifecycle (a loop, not a ratchet).
         * @enum {string}
         */
        State: "incubating" | "warming" | "armed" | "managing";
        /**
         * ThesisDetail
         * @description The full thesis for the Cockpit — a wire model (no tenant_id) so generated FE types never bind
         *     to the domain Thesis. Sub-objects reuse the domain value types (no transform needed, like the
         *     catalyst surface on CallCardResponse).
         */
        ThesisDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Name */
            name: string;
            /** Narrative */
            narrative: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket
             * @default []
             */
            basket: components["schemas"]["BasketMember"][];
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["Segment"][];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Catalysts
             * @default []
             */
            catalysts: components["schemas"]["Catalyst"][];
            /**
             * Kill Criteria
             * @default []
             */
            kill_criteria: components["schemas"]["KillCriterion"][];
            position?: components["schemas"]["Position"] | null;
        };
        /**
         * ThesisSummary
         * @description Lightweight list item for the Board (the full thesis comes from GET /theses/{id}).
         */
        ThesisSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket Size
             * @default 0
             */
            basket_size: number;
            /** Narrative */
            narrative: string;
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "auto" | "flag" | "human";
        /** TriggerRefOut */
        TriggerRefOut: {
            /** Label */
            label: string;
            kind: components["schemas"]["Kind"];
            grade?: components["schemas"]["Grade"] | null;
            /** Ticker */
            ticker?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["ProvenanceOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "watching" | "not_yet" | "flip_only" | "starter_entry" | "core_entry" | "managing";
        /**
         * WorkbenchScored
         * @description The Workbench scored read for a thesis: its value-chain segments + the scored members (the UI groups
         *     by `member.segment`). Re-derived on read — never persisted.
         */
        WorkbenchScored: {
            /**
             * Thesis Id
             * Format: uuid
             */
            thesis_id: string;
            /**
             * Asof
             * Format: date
             */
            asof: string;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["Segment"][];
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["ScoredMemberOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_theses_theses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisSummary"][];
                };
            };
        };
    };
    get_thesis_theses__thesis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_theses__thesis_id__call_get: {
        parameters: {
            query: {
                /** @description as-of date; the call uses no data knowable after it */
                asof: string;
            };
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scored_workbench_theses__thesis_id__scored_get: {
        parameters: {
            query: {
                /** @description as-of date; the scores use no data knowable after it */
                asof: string;
            };
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbenchScored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_securities_workbench_securities_get: {
        parameters: {
            query?: {
                /** @description ticker or name fragment; a discovery net over the master */
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityMatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_scoring_facts_workbench_securities__security_id__extract_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedFact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_flag_candidate_workbench_facts_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractedFact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_workbench_theses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteThesisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ratify_fact_workbench_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatifyRevenueMix"] | components["schemas"]["RatifyShares"] | components["schemas"]["RatifyCashBurn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatifiedFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
