/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Theses */
        get: operations["list_theses_theses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theses/{thesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thesis */
        get: operations["get_thesis_theses__thesis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theses/{thesis_id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Call
         * @description Recompute the CallCard live at ``asof`` — a READ-ONLY path. The signal stream is re-derived
         *     from the bitemporal facts (no persisted firing layer), so a given ``asof`` is deterministic and a
         *     refetch / as-of-slider scrub / poll writes nothing. The accountability ``calls`` log is written
         *     by the batch ``pipeline.run`` (the official call of record), never by this GET.
         */
        get: operations["get_call_theses__thesis_id__call_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/scored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scored
         * @description Re-derive the per-name Workbench scores live at ``asof`` — a READ-ONLY path (Option B; nothing
         *     persists). Mirrors the call endpoint: load the thesis (404 + its tenant), thread ``thesis.tenant_id``
         *     into every scoring fact read so a production thesis scores off production's facts.
         */
        get: operations["get_scored_workbench_theses__thesis_id__scored_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Securities
         * @description Search the current tenant's security master for names to PLACE into a basket (the authoring
         *     typeahead, Slice 4b). A DISCOVERY NET (INVARIANT #2): exact master rows for the operator to pick from
         *     — never a fuzzy decision, never an ingest (no ``allow_live``). No match -> ``[]``; the operator's pick
         *     carries the exact ``security_id``. Tenant from the deployment resolver (which universe to author in).
         */
        get: operations["search_securities_workbench_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/securities/{security_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Extract Scoring Facts
         * @description Auto-EXTRACT candidate scoring facts for a security from its latest SEC 10-Q/10-K (Slice hybrid-1) —
         *     the three-tier hybrid: AUTO pre-fills the clean facts, FLAG carries the raw value + a detected risk + the
         *     located passage (the operator ratifies the composition), HUMAN (purity) is LOCATED only and never
         *     auto-valued. An EXPLICIT operator action (cache-first, live SEC), never fired on a render. The extractor
         *     never DECIDES — the operator confirms (hybrid-2). Requires ``ALPHADECK_USER_AGENT`` (SEC etiquette).
         *
         *     PURITY ESTIMATE (SURFACE 1b): with ``thesis_id``, the grounded purity seam proposes an UNVERIFIED
         *     on-thesis % for the revenue_mix candidate — read ONLY from its located segment passage, with the thesis
         *     narrative selecting the segment. It attaches ``value`` + ``estimate_source="llm_proposed"`` (the passage
         *     stays on the candidate), never a fact until the operator ratifies. PURITY-ONLY: ``thesis_id`` touches no
         *     other candidate, and its absence (or a fail-open decline) leaves purity as today's HUMAN (located, no value).
         */
        get: operations["extract_scoring_facts_workbench_securities__security_id__extract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/facts/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Flag Candidate
         * @description Draft a plain-English explanation of a FLAG candidate, grounded in its located passage — the one LLM
         *     seam (M4b). A DISPLAY aid shown ALONGSIDE the raw passage; it NEVER becomes a fact.
         *
         *     Note what is absent: no ``get_conn``, no tenant, no write. The explanation rides a separate rail that
         *     dead-ends at the screen — the ratified number can only ever come from the operator's typed field on
         *     ``/facts`` (INVARIANT #3). The prompt asks the model not to state the final value; this missing
         *     connection is what guarantees it can't become one.
         *
         *     Fail-open by contract: any LLM trouble (no ``ANTHROPIC_API_KEY``, timeout, SDK error, or the model
         *     declining to ground it) returns 200 with ``{explanation: "", grounded: false}`` — NEVER a 5xx. The facts
         *     panel renders identically to today. (FLAG-only: a non-FLAG candidate returns the same empty signal.)
         */
        post: operations["explain_flag_candidate_workbench_facts_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote
         * @description Promote a structured thesis to the Board (Incubating) — the app's FIRST mutation. Create (``id``
         *     null) or update (``id`` set); the value-chain structure (segments + placements + authorship) persists
         *     via ``thesis_repo.upsert`` (the existing operational save path). The tenant comes from the deployment
         *     resolver, NOT the body. Scores are never sent and never persist — they re-derive on read.
         *
         *     Write-side guards (INVARIANT #2): ``authored_by`` is HONORED from the body — the human path sends
         *     ``operator_set``; the S5 draft/ratify path sends ``system_drafted`` (a kept draft) or ``operator_edited``
         *     (an edited one) — not coerced, so a drafted placement stays drafted until the operator ratifies it. Every
         *     placed ``security_id`` must be an EXACT member of this tenant's master (fail-closed — a caller-supplied
         *     id is never trusted), the single point where bound #2 is enforced now that the S5 drafter returns a draft
         *     and writes nothing itself. And the id is CANONICALIZED: a multi-sibling CIK's non-primary row (a foreign
         *     ordinary / warrant / dual-class sibling the draft happened to surface) is re-pointed to the CIK's primary
         *     instrument before the spine write (``master.canonicalize_ids`` — the same pick as ``ids_for_ciks``), so
         *     the basket stores the instrument the operator actually trades; the response carries the canonical
         *     ticker.
         */
        post: operations["promote_workbench_theses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Produce Terms
         * @description Produce + PERSIST the thesis's tiered discovery term set — the SIGNAL/BROAD keywords the EDGAR precision
         *     filter reads. Two sources, two authorities: the operator's ``seeds`` (canonical compounds) are anchored as
         *     ``operator_set`` SIGNAL — the RECALL guarantor against keyword-gen's non-determinism — and keyword-gen
         *     PROPOSES the rest, which a DETERMINISTIC guard tiers (``system_drafted``; the "is this discriminating?"
         *     decision is OFF the LLM, ``workbench.term_set``). This is the WRITER seam: the LLM lives HERE, never in
         *     ``promote`` (the pure structured writer).
         *
         *     REGENERABLE + CONVERGENT: a re-POST PRESERVES every operator-authored entry — ``operator_set`` seeds AND
         *     ``operator_edited`` promotions/demotions (from the edit-UI), each VERBATIM (term + tier + authorship) — while
         *     RE-ROLLING only the ``system_drafted`` LLM-proposed terms. So the inspect-and-tune loop re-rolls the
         *     augmentation without ever dropping an operator decision (a demoted SIGNAL→BROAD term comes back BROAD, not
         *     re-promoted). New ``req.seeds`` are added as fresh SIGNAL. Returns the thesis so the operator can INSPECT the
         *     stored SIGNAL/BROAD split. Fail-open: no key / blank narrative + no seeds → an empty set is stored (the draft
         *     then 503s "term set is empty" — surfaced, never a silent recall fallback). It sources NO number (#3) — terms
         *     only — and writes ONLY ``term_set`` (the narrow ``set_term_set``).
         */
        post: operations["produce_terms_workbench_theses__thesis_id__terms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/terms/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Edit Terms
         * @description SAVE the operator's manually-edited term set DIRECTLY — NO LLM (the LLM lives only in ``POST .../terms``;
         *     this mirrors LLM-out-of-promote, a structural boundary, not a convention). The operator adds a seed
         *     (→ ``operator_set`` SIGNAL), removes a term, promotes BROAD→SIGNAL or demotes SIGNAL→BROAD
         *     (→ ``operator_edited``); an UNTOUCHED ``system_drafted`` BROAD term keeps its authorship so a later
         *     regenerate can re-roll it. Authorship is STAMPED server-side by diffing the stored set
         *     (``stamp_edited_term_set``), never trusted from the body. A full-set replace via the narrow
         *     ``set_term_set`` (the SOLE writer; ``upsert`` never names ``term_set`` — the structural wipe-guard stays
         *     intact). Sources NO number (#3) — structure/config only. 422 on an empty term or a case-insensitive
         *     duplicate. An empty ``terms`` clears the set (a visible operator choice; the draft then 503s "term set is
         *     empty").
         */
        put: operations["edit_terms_workbench_theses__thesis_id__terms_edit_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/recommend-tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Tiers Endpoint
         * @description Recommend a tier (signal/broad) + a one-line reason per term in the thesis's term set — the LLM
         *     RECOMMENDS, the operator DECIDES (INVARIANT #10). DISPLAY-ONLY + RESPONSE-ONLY: no writer is called
         *     (``set_term_set`` / ``upsert`` never appear), so a recommendation can NEVER become a persisted tier — it
         *     rides on its OWN wire type (``list[TierRecommendation]``), never on ``ThesisDetail.term_set``, and the
         *     operator confirms it via the EXISTING tier toggle (``PUT .../terms/edit``), where ``stamp_edited_term_set``
         *     stamps ``operator_edited`` (never an LLM-authored SIGNAL). The model judges each term INDEPENDENTLY of its
         *     current tier; the FE does the agree/disagree compare. OFF ``produce_term_set``'s determinism path (advisory
         *     metadata, never a tier the producer applies — recall stays sacred, #9). Fail-open: no key / model trouble ->
         *     ``[]`` (the chips render with no recommendation). Sources NO number (#3) — a tier label + a reason string.
         */
        post: operations["recommend_tiers_endpoint_workbench_theses__thesis_id__recommend_tiers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/draft-chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Draft Chain
         * @description KICK OFF the narrative→chain draft as a background JOB and return immediately (**202** + ``job_id``); the
         *     FE polls ``GET .../draft-chain/jobs/{job_id}`` for the result. The draft takes minutes (EDGAR discovery + the
         *     Opus tail-sweep + decompose + narrate); held open as one request it blew past nginx's 300s proxy timeout —
         *     the browser 504'd while the backend kept billing. Only the DELIVERY changed; ``execute_draft`` is unchanged.
         *
         *     The IN-FLIGHT 409 guard lives HERE now (one running draft per thesis — ``DraftInFlight`` → HTTP 409, so a
         *     double-click / stray retry can never launch a parallel Opus pass). The job runs in a daemon thread that opens
         *     its OWN DB connection (it OUTLIVES this request — the ``get_thesis_or_404`` conn is closed once the 202 is
         *     sent). Discovery-not-ready / unexpected faults become a VISIBLE *failed* job on the poll (never a silent empty
         *     draft, #9); a benign fail-open (no key / the model declined) is a *done* job with an empty draft. RESPONSE-ONLY
         *     (the job writes only its in-memory result — no fact, no promote). A completed job additionally dumps a
         *     WRITE-ONLY run-of-record artifact (``data/draft_runs/`` — the DISCOVER stage's ``calls``-log analogue:
         *     the term set as used, the dials, the full draft); nothing in the app reads it, and a failed write is
         *     logged + swallowed, never a failed draft.
         */
        post: operations["start_draft_chain_workbench_theses__thesis_id__draft_chain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/draft-chain/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft Chain Job
         * @description POLL a kicked-off draft job. ``done`` → the ``result`` (a ChainDraftOut); ``failed`` → an operator-facing
         *     ``error`` (discovery-not-ready, a timeout, or an unexpected fault — VISIBLE, #9). **404** if the job is
         *     unknown / expired, or the registry was wiped by a restart — the FE shows a visible "draft was lost" (never an
         *     infinite spinner). The job_id must belong to this thesis.
         */
        get: operations["get_draft_chain_job_workbench_theses__thesis_id__draft_chain_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Saved Runs
         * @description List this thesis's saved draft-run artifacts, newest-first — the run-loader picker's source. Pure file
         *     read (no compute, no EDGAR). **404** when the run loader is disabled (so the FE picker is absent).
         */
        get: operations["list_saved_runs_workbench_theses__thesis_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/theses/{thesis_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Saved Run
         * @description Load one saved run's inner draft as a ``ChainDraftOut`` — the SAME shape the draft endpoint returns, so
         *     the FE hands it straight to the editor's ``applyDraft`` (no re-draft, no refetch). **404** when the loader
         *     is disabled, or for an unknown / traversal ``run_id``; **422** if a stale artifact no longer validates
         *     against the current schema.
         */
        get: operations["get_saved_run_workbench_theses__thesis_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbench/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ratify Fact
         * @description Ratify an extracted candidate -> write the scoring fact (hybrid-2a) — the app's first fact-WRITE. The
         *     operator confirms/edits a candidate (AUTO as-is, FLAG the composition, HUMAN purity the value); this
         *     persists it via the existing ``ingest_*`` so the meter re-derives on the next scored read.
         *
         *     WRITE-SIDE TENANT DISCIPLINE: the security must be in the CURRENT tenant's master (fail-closed) — the
         *     tenant is the deployment resolver's, but the ``security_id`` is caller-supplied, so a foreign/unknown id
         *     must not write a junk fact. ``source`` is preserved (the candidate's basis, e.g. ``10-k-segment``);
         *     ``ratified_by`` is stamped "operator"; the fact is append-only (a re-ratify is a new row, latest-wins).
         *
         *     ``vouched`` records whether the operator confirmed the shown ``estimate`` as-is or overrode it — PROVENANCE
         *     for the drift-cron + the agree/disagree signal, NEVER a scoring input (all vouched states score identically).
         */
        post: operations["ratify_fact_workbench_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Archetype
         * @description A basket member's role in expressing the thesis.
         * @enum {string}
         */
        Archetype: "leader" | "high_beta" | "lotto" | "shovel" | "adjacent" | "fund";
        /**
         * Authorship
         * @description Who placed a basket member in its value-chain segment (the Workbench authorship seam).
         *
         *     The MVP writes only the operator values; ``SYSTEM_DRAFTED`` is present now so the seam already
         *     supports the bounded LLM drafter (the next slice) without a later schema change.
         * @enum {string}
         */
        Authorship: "system_drafted" | "operator_set" | "operator_edited";
        /** BasketMember */
        BasketMember: {
            /** Ticker */
            ticker: string;
            /** Role */
            role: string;
            archetype?: components["schemas"]["Archetype"] | null;
            /** Security Id */
            security_id?: string | null;
            /** Detail */
            detail?: string | null;
            /** Segment */
            segment?: string | null;
            /** Thesis Fit */
            thesis_fit?: string | null;
            /** Conviction */
            conviction?: number | null;
            /** @default operator_set */
            authored_by: components["schemas"]["Authorship"];
        };
        /**
         * CallCardResponse
         * @description The CallCard as served — the domain card plus resolved provenance URLs.
         */
        CallCardResponse: {
            /**
             * Thesis Id
             * Format: uuid
             */
            thesis_id: string;
            /**
             * Asof
             * Format: date
             */
            asof: string;
            state: components["schemas"]["State"];
            verdict: components["schemas"]["Verdict"];
            conviction_grade?: components["schemas"]["Grade"] | null;
            confirmation_grade?: components["schemas"]["Grade"] | null;
            entry_grade?: components["schemas"]["Grade"] | null;
            /** Armed Security Id */
            armed_security_id?: string | null;
            /** Expression */
            expression: string;
            /** Exit By */
            exit_by?: string | null;
            /** Arm Until */
            arm_until?: string | null;
            /**
             * Catalyst Surface
             * @default []
             */
            catalyst_surface: components["schemas"]["Catalyst"][];
            /** Confidence */
            confidence?: number | null;
            key_conviction: components["schemas"]["KeyState"];
            key_confirmation: components["schemas"]["KeyState"];
            /**
             * Triggers Fired
             * @default []
             */
            triggers_fired: components["schemas"]["TriggerRefOut"][];
            /**
             * Risk Signals
             * @default []
             */
            risk_signals: components["schemas"]["TriggerRefOut"][];
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Counter Case
             * @default
             */
            counter_case: string;
            /** Safe Sleeve */
            safe_sleeve?: string | null;
            /**
             * Armed Members
             * @default []
             */
            armed_members: components["schemas"]["MemberCallOut"][];
            /**
             * Watch Members
             * @default []
             */
            watch_members: components["schemas"]["MemberCallOut"][];
        };
        /** Catalyst */
        Catalyst: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Kind */
            kind?: string | null;
            /** When Date */
            when_date?: string | null;
            /** When Label */
            when_label?: string | null;
        };
        /**
         * ChainDraftOut
         * @description The narrative→chain draft (Slice 5b): the value-chain SEGMENTS the model proposed + each proposed name
         *     resolved against the master to PLACED / AMBIGUOUS / ABSENT (exact membership decides — INVARIANT #2).
         *
         *     RESPONSE-ONLY and value-free: it carries NO score/number field, and the endpoint persists NOTHING — a
         *     placed name is UNSCORED until the operator extract→ratifies it, and the operator's promote is the only
         *     writer. ``segments`` / ``placements`` reuse the resolver's domain result types directly (the wire is the
         *     resolver's output). ``report`` is the run's honesty report (coverage / capped terms / tail-sweep /
         *     narration — ``DraftReportOut``): ALWAYS set by ``execute_draft``, optional on the wire only so a reader
         *     handles its absence.
         */
        ChainDraftOut: {
            /**
             * Thesis Id
             * Format: uuid
             */
            thesis_id: string;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["ResolvedSegment"][];
            /**
             * Placements
             * @default []
             */
            placements: components["schemas"]["ResolvedPlacement"][];
            report?: components["schemas"]["DraftReportOut"] | null;
        };
        /**
         * DraftCoverageOut
         * @description How much of the universe the draft's EFTS enumeration actually covered (the #9 rule-2/3 instrument on
         *     the wire): a sub-threshold gap used to pass looking complete (logged only); now the pages fetched vs
         *     attempted — and the TERMS whose pages are still missing — ride every draft to the operator. RUN state,
         *     display-only, never persisted.
         */
        DraftCoverageOut: {
            /** Pages Ok */
            pages_ok: number;
            /** Pages Attempted */
            pages_attempted: number;
            /**
             * Failed Terms
             * @default []
             */
            failed_terms: string[];
        };
        /**
         * DraftJobRef
         * @description The 202 kick-off body — the draft started as a background JOB (it takes minutes; held open it 504'd at the
         *     proxy). The FE polls ``GET .../draft-chain/jobs/{job_id}`` for the result. Only the DELIVERY changed; the
         *     draft logic is unchanged.
         */
        DraftJobRef: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "failed";
        };
        /**
         * DraftJobStatus
         * @description The poll body. ``done`` carries the ``result`` (the ChainDraftOut); ``failed`` carries an operator-facing
         *     ``error`` (discovery-not-ready, a timeout, or an unexpected fault — VISIBLE, never a silent empty draft, #9).
         *     A benign fail-open (no key / the model declined) is ``done`` with an EMPTY draft, not a failure.
         */
        DraftJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "failed";
            result?: components["schemas"]["ChainDraftOut"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * DraftReportOut
         * @description The draft run's honesty report — every formerly-silent recall-loss mode, named per run (#9 rules 2/3):
         *     EFTS coverage, the hit-capped terms (enumeration truncated at the cap — deep hits not searched), the
         *     tail-sweep outcome (``ran`` / ``failed`` / ``skipped`` — a failed sweep is no longer indistinguishable from
         *     "no foreign names exist"), and the narration fill (M of N placed/verify names carrying thesis-fit prose).
         *     Value-free (#3) and RESPONSE-ONLY — display run state, never a fact, never persisted; the Workbench strip
         *     renders it quiet at 100% healthy, loud on any gap (inverse loudness).
         */
        DraftReportOut: {
            coverage: components["schemas"]["DraftCoverageOut"];
            /**
             * Capped Terms
             * @default []
             */
            capped_terms: string[];
            /**
             * Tail Sweep
             * @enum {string}
             */
            tail_sweep: "ran" | "failed" | "skipped";
            /** Narration Needed */
            narration_needed: number;
            /** Narration Filled */
            narration_filled: number;
        };
        /**
         * EditTermsRequest
         * @description Body for ``PUT /theses/{id}/terms/edit`` — the operator's full, edited term set, saved DIRECTLY (no LLM,
         *     mirroring LLM-out-of-promote). Authorship is re-stamped server-side: an untouched ``system_drafted`` BROAD
         *     term keeps its authorship so a later regenerate can re-roll it; only operator-touched entries become
         *     ``operator_set`` (added) / ``operator_edited`` (re-tiered). An empty list clears the set (a visible operator
         *     choice).
         */
        EditTermsRequest: {
            /**
             * Terms
             * @default []
             */
            terms: components["schemas"]["TermEdit"][];
        };
        /**
         * Evidence
         * @description Immutable reference to a filing / data point.
         */
        Evidence: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Ref */
            ref: string;
            /** Date Label */
            date_label?: string | null;
        };
        /**
         * ExtractedFact
         * @description One candidate scoring fact for a security, with its tier, raw value(s), located evidence, and flags.
         *     The shape mirrors the three ``ingest_*`` writers: shares -> ``value``; cash_burn -> ``cash_usd`` +
         *     ``quarterly_burn_usd``; revenue_mix (purity) -> no value (HUMAN).
         */
        ExtractedFact: {
            /** Fact Type */
            fact_type: string;
            tier: components["schemas"]["Tier"];
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Value */
            value?: number | null;
            /** Cash Usd */
            cash_usd?: number | null;
            /** Quarterly Burn Usd */
            quarterly_burn_usd?: number | null;
            /** Flags */
            flags?: string[];
            /** Located Passages */
            located_passages?: components["schemas"]["LocatedPassage"][];
            /** Estimate Source */
            estimate_source?: string | null;
        };
        /**
         * FlagExplanationOut
         * @description The model-drafted, plain-English explanation of a FLAG candidate, shown ALONGSIDE the raw passage.
         *
         *     Deliberately carries NO value field: it is display-only and never rides the ratify rail (the ratified
         *     number comes solely from the operator's typed field on ``RatifyFactRequest``). ``grounded=False`` (with an
         *     empty ``explanation``) is the honest no-explanation / fail-open signal — the UI shows the raw passage and
         *     manual ratify exactly as today. (INVARIANT #3.)
         */
        FlagExplanationOut: {
            /** Explanation */
            explanation: string;
            /** Grounded */
            grounded: boolean;
        };
        /**
         * Grade
         * @enum {string}
         */
        Grade: "flip" | "core";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeyState
         * @description One of the two keys (Conviction / Confirmation) rendered on the call card.
         */
        KeyState: {
            /** Turned */
            turned: boolean;
            /** Label */
            label: string;
            /** Detail */
            detail?: string | null;
        };
        /** KillCriterion */
        KillCriterion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * Kind
         * @description What produced the signal (extensible).
         * @enum {string}
         */
        Kind: "insider" | "catalyst" | "theme_conviction" | "technical_breakout" | "laggard" | "squeeze" | "etf_launch" | "etf_flow" | "dilution_risk";
        /**
         * LocatedPassage
         * @description A deterministically-retrieved passage that backs a fact — the evidence put in front of the operator
         *     (or, later, S5). Retrieval only: a keyword/section match, never a model's reading.
         */
        LocatedPassage: {
            /** Kind */
            kind: string;
            /** Source Ref */
            source_ref: string;
            /** Anchor */
            anchor: string;
            /** Excerpt */
            excerpt: string;
        };
        /**
         * MemberCallOut
         * @description One basket member's call in the per-member ranked menu (M5 Part A). `armed_members` is ranked
         *     (the headline is [0]); `watch_members` are confirmation-only ("moving, no conviction yet").
         */
        MemberCallOut: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker?: string | null;
            verdict?: components["schemas"]["Verdict"] | null;
            conviction_grade?: components["schemas"]["Grade"] | null;
            confirmation_grade?: components["schemas"]["Grade"] | null;
            entry_grade?: components["schemas"]["Grade"] | null;
            /** Confidence */
            confidence?: number | null;
            /** Exit By */
            exit_by?: string | null;
            /** Arm Until */
            arm_until?: string | null;
            /**
             * Lapsing
             * @default false
             */
            lapsing: boolean;
            /**
             * Theme Armed
             * @default false
             */
            theme_armed: boolean;
            /**
             * Triggers
             * @default []
             */
            triggers: components["schemas"]["TriggerRefOut"][];
        };
        /**
         * PlacementStatus
         * @enum {string}
         */
        PlacementStatus: "placed" | "verify" | "ambiguous" | "absent";
        /**
         * Position
         * @description Populated once the operator logs a fill — its presence drives the Managing state.
         */
        Position: {
            /** Entry Price */
            entry_price?: number | null;
            /** Current Price */
            current_price?: number | null;
            /** Opened On */
            opened_on?: string | null;
        };
        /**
         * ProduceTermsRequest
         * @description Body for ``POST /theses/{id}/terms`` (optional). ``seeds`` are the operator-anchored canonical compounds
         *     (e.g. the known psychedelic compounds) — persisted as operator-authored SIGNAL, the recall guarantor against
         *     keyword-gen non-determinism. Omitted / empty seeds -> regenerate preserves the thesis's EXISTING operator
         *     seeds and just re-rolls the LLM-proposed terms.
         */
        ProduceTermsRequest: {
            /**
             * Seeds
             * @default []
             */
            seeds: string[];
        };
        /**
         * PromoteThesisRequest
         * @description The promote/update payload — a thesis-with-chain. The router builds a domain Thesis (the
         *     segment-consistency validator runs) under the CURRENT tenant (the resolver, not the body), then upserts
         *     it (create when `id` is null, update otherwise). Scores are NOT sent — they re-derive on read.
         *     `authored_by` is STAMPED server-side (the human path authors `operator_set`), not taken from the body.
         */
        PromoteThesisRequest: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Narrative */
            narrative: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket
             * @default []
             */
            basket: components["schemas"]["BasketMember"][];
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["Segment"][];
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /** Source */
            source: string;
            /** Ref */
            ref: string;
            /** Url */
            url?: string | null;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
        };
        /** RatifiedFactOut */
        RatifiedFactOut: {
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Fact Type */
            fact_type: string;
        };
        /** RatifyCashBurn */
        RatifyCashBurn: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Note */
            note?: string | null;
            /** Estimate */
            estimate?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            fact_type: "cash_burn";
            /** Cash Usd */
            cash_usd: number;
            /** Quarterly Burn Usd */
            quarterly_burn_usd: number;
        };
        /** RatifyRevenueMix */
        RatifyRevenueMix: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Note */
            note?: string | null;
            /** Estimate */
            estimate?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            fact_type: "revenue_mix";
            /** Segment Label */
            segment_label: string;
            /** Mix Pct */
            mix_pct: number;
        };
        /** RatifyShares */
        RatifyShares: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Note */
            note?: string | null;
            /** Estimate */
            estimate?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            fact_type: "shares_outstanding";
            /** Shares */
            shares: number;
        };
        /**
         * ResolvedPlacement
         * @description A proposed name after resolution against the master. ``security_id`` is set IFF ``PLACED``;
         *     ``candidates`` is non-empty IFF ``AMBIGUOUS``. The model's ``name`` / ``ticker`` / ``prose`` are
         *     preserved (so the UI can show what the model proposed even when it didn't resolve).
         *
         *     ``matched_terms`` are the discovery keyword(s) the name's CIK hit (provenance — INVARIANT #6, and the
         *     on-screen tell for a colliding seed per #9: a placed name shows WHY it surfaced). Empty for an off-universe
         *     name resolved by the master rather than discovered by a term. Never a number (#3 — a keyword string).
         *
         *     ``discovery_source`` records WHERE the name came from (provenance — INVARIANT #6): ``"edgar"`` = matched a
         *     CIK in the EDGAR-discovered universe; ``"off_universe"`` = resolved OUTSIDE that universe, via the
         *     sweep-augmented context. **It is NOT a hard claim the tail-sweep's web-search sourced the name** (``decompose``
         *     may surface an off-universe name from its own knowledge) — it means only "off the deterministic universe,"
         *     never "tail-sweep found this." Display-only like ``matched_terms``: never a number (#3), never promoted onto a
         *     ``BasketMember`` (#2). Defaults ``"edgar"`` (the conservative no-pill state) and is set ``"off_universe"`` in
         *     exactly ONE place — the ``_match_discovered_cik`` fork — so a stray construction can never over-claim.
         *
         *     ``sector`` / ``exchange`` / ``listing_status`` / ``category`` are machine-parsed IDENTITY carried from the master (enriched
         *     just-in-time from EDGAR submissions before resolution) — display-only like ``matched_terms``: never a number
         *     (#3), never promoted onto a ``BasketMember`` (#2). ``listing_status`` is a LISTING-PRESENCE heuristic
         *     (``"active"`` / ``"inactive"``), NOT a delisting verdict: a PLACED name whose master row reads ``"inactive"``
         *     is DOWNGRADED to AMBIGUOUS (never auto-placed) with its own row as the single pick — a frictionless rescue,
         *     surfaced with a HEDGED flag ("no current listing found in EDGAR"), so a false-inactive costs one extra click,
         *     never a silent drop (#9). ``None`` when the row is un-enriched (the honest fallback — no flag, no gate).
         *
         *     ``off_thesis`` surfaces the NARRATOR's already-made "this name doesn't fit the thesis" opinion as a bit (the
         *     ``prose`` is the why) — display-only like ``matched_terms`` / ``discovery_source``: never a number (#3), never
         *     promoted onto a ``BasketMember`` (#2), never on the call path. It RECOMMENDS, never removes: a flagged name
         *     STAYS placed (membership is deterministic exact-CIK, #2 / #9 — never a silent drop) with a ``remove`` the
         *     OPERATOR clicks (#10). Set at the narration MERGE (``app.routers.workbench.execute_draft``), not at resolution
         *     — so it defaults ``False`` on every construction path here. COVERAGE = reconciler-appended collisions (the
         *     unnarrated PLACED/VERIFY names the narration pass fills): the boilerplate-collision flood the flag exists to
         *     catch. The organizer's OWN placements carry prose and aren't re-judged — an organizer-placed off-thesis name
         *     reading unflagged is SCOPE, not a bug. Fail-open: no narration → ``False`` (never flag on missing data).
         */
        ResolvedPlacement: {
            /** Name */
            name: string;
            /** Ticker */
            ticker: string | null;
            /** Prose */
            prose: string;
            /** Segment */
            segment: string;
            status: components["schemas"]["PlacementStatus"];
            /** Security Id */
            security_id?: string | null;
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["SecurityCandidate"][];
            /**
             * Matched Terms
             * @default []
             */
            matched_terms: string[];
            /**
             * Discovery Source
             * @default edgar
             * @enum {string}
             */
            discovery_source: "edgar" | "off_universe";
            /** Sector */
            sector?: string | null;
            /** Exchange */
            exchange?: string | null;
            /** Listing Status */
            listing_status?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Off Thesis
             * @default false
             */
            off_thesis: boolean;
        };
        /** ResolvedSegment */
        ResolvedSegment: {
            /** Label */
            label: string;
            /** Descriptor */
            descriptor?: string | null;
        };
        /**
         * SavedRunSummary
         * @description One saved draft-run artifact's summary for the run-loader picker (the cheap label fields — never the
         *     draft itself; the detail endpoint returns the inner ``ChainDraftOut``). RUN metadata only: no score, no
         *     number (#3). ``run_id`` is the artifact's filename stem (the detail-endpoint path segment).
         */
        SavedRunSummary: {
            /** Run Id */
            run_id: string;
            /** Written At */
            written_at?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Placement Count */
            placement_count: number;
            /** Segment Count */
            segment_count: number;
        };
        /**
         * ScoredFigureOut
         * @description One meter/figure on the wire: the 0-4 pip (null = "—"/no data), the raw value, and the provenance
         *     chips ("behind the scores"). market_cap carries `value` only (pips null — a figure, not a meter).
         */
        ScoredFigureOut: {
            /** Pips */
            pips?: number | null;
            /** Value */
            value?: number | null;
            /**
             * Provenance
             * @default []
             */
            provenance: components["schemas"]["ProvenanceOut"][];
        };
        /**
         * ScoredMemberOut
         * @description A basket member scored for the Workbench — the four meters + the market-cap figure + the fit label.
         */
        ScoredMemberOut: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker?: string | null;
            /** Name */
            name?: string | null;
            /** Sector */
            sector?: string | null;
            /** Exchange */
            exchange?: string | null;
            /** Category */
            category?: string | null;
            archetype?: components["schemas"]["Archetype"] | null;
            archetype_hint?: components["schemas"]["Archetype"] | null;
            /** Segment */
            segment?: string | null;
            purity: components["schemas"]["ScoredFigureOut"];
            runway: components["schemas"]["ScoredFigureOut"];
            catalysts: components["schemas"]["ScoredFigureOut"];
            dilution: components["schemas"]["ScoredFigureOut"];
            market_cap: components["schemas"]["ScoredFigureOut"];
            /** Fit */
            fit: string;
            /**
             * Unconfirmed Estimates
             * @default 0
             */
            unconfirmed_estimates: number;
        };
        /**
         * SecurityCandidate
         * @description A master row offered for the operator to pick (ticker + CIK shown so a homonym is disambiguated).
         */
        SecurityCandidate: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Cik */
            cik?: string | null;
        };
        /**
         * SecurityMatchOut
         * @description A security-master match for the Workbench's add-a-name typeahead (Slice 4b). The operator picks the
         *     exact row; its ``security_id`` is then placed into the basket. A discovery net over the EXISTING
         *     per-tenant master (INVARIANT #2) — every match is a real member, nothing is ingested or guessed.
         */
        SecurityMatchOut: {
            /**
             * Security Id
             * Format: uuid
             */
            security_id: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Cik */
            cik?: string | null;
        };
        /**
         * Segment
         * @description A link in the thesis's value chain (the Workbench decomposition) — STRUCTURE, not a score.
         *
         *     The per-segment candidate count is DERIVED on read (``len`` of members in the link), never stored.
         */
        Segment: {
            /** Label */
            label: string;
            /** Descriptor */
            descriptor?: string | null;
        };
        /**
         * State
         * @description Thesis lifecycle (a loop, not a ratchet).
         * @enum {string}
         */
        State: "incubating" | "warming" | "armed" | "managing";
        /**
         * TermEdit
         * @description One operator-edited term in the manual save (``PUT .../terms/edit``). The operator owns ``term`` +
         *     ``tier``; ``authored_by`` is NOT in the body — the server stamps it by diffing against the stored set (a
         *     naive client must not be able to mark a term ``operator_edited`` and freeze it against regenerate).
         */
        TermEdit: {
            /** Term */
            term: string;
            tier: components["schemas"]["TermTier"];
        };
        /**
         * TermSetEntry
         * @description One discovery keyword in the thesis's persisted, tiered term set — the SIGNAL/BROAD input the EDGAR
         *     precision filter reads (it decides which EFTS hits PLACE a company).
         *
         *     ``term`` is the EFTS phrase; ``tier`` is SIGNAL or BROAD (see ``TermTier``). ``authored_by`` + ``source``
         *     carry provenance so the future operator-edit UI (confirm / override a term's tier) is a PURE addition on
         *     the same object: the deterministic ``/terms`` guard writes ``system_drafted``; an operator override becomes
         *     ``operator_set`` / ``operator_edited``. It is STRUCTURE / config — never a fact or a number (#3).
         */
        TermSetEntry: {
            /** Term */
            term: string;
            tier: components["schemas"]["TermTier"];
            /** @default system_drafted */
            authored_by: components["schemas"]["Authorship"];
            /** Source */
            source?: string | null;
        };
        /**
         * TermTier
         * @description A discovery keyword's tier in the thesis's persisted term set — the precision filter's INPUT.
         *
         *     SIGNAL = a discriminating compound / drug / mechanism token; a single EFTS hit PLACES a company.
         *     BROAD = a collision-prone abbreviation or disease/indication term; counts only toward the >=2-distinct
         *     rule, never places alone. The thesis OWNS this tiering (a deterministic guard sets the default; the
         *     operator overrides later) and discovery READS it — the "is this discriminating?" decision is OFF the LLM.
         * @enum {string}
         */
        TermTier: "signal" | "broad";
        /**
         * ThesisDetail
         * @description The full thesis for the Cockpit — a wire model (no tenant_id) so generated FE types never bind
         *     to the domain Thesis. Sub-objects reuse the domain value types (no transform needed, like the
         *     catalyst surface on CallCardResponse).
         */
        ThesisDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Name */
            name: string;
            /** Narrative */
            narrative: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket
             * @default []
             */
            basket: components["schemas"]["BasketMember"][];
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["Segment"][];
            /**
             * Term Set
             * @default []
             */
            term_set: components["schemas"]["TermSetEntry"][];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Catalysts
             * @default []
             */
            catalysts: components["schemas"]["Catalyst"][];
            /**
             * Kill Criteria
             * @default []
             */
            kill_criteria: components["schemas"]["KillCriterion"][];
            position?: components["schemas"]["Position"] | null;
        };
        /**
         * ThesisSummary
         * @description Lightweight list item for the Board (the full thesis comes from GET /theses/{id}).
         */
        ThesisSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker?: string | null;
            /**
             * Basket Size
             * @default 0
             */
            basket_size: number;
            /** Narrative */
            narrative: string;
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "auto" | "flag" | "human";
        /**
         * TierRecommendation
         * @description An advisory tier recommendation for ONE term (INVARIANT #10 — the LLM recommends, the operator decides).
         *     DISPLAY-ONLY: it is the response of ``POST .../recommend-tiers``, never persisted, never mutating
         *     ``authored_by``. The operator confirms it via the EXISTING tier toggle (``PUT .../terms/edit``), where
         *     ``stamp_edited_term_set`` stamps ``operator_edited``. Deliberately a SEPARATE wire type — it never rides on
         *     ``ThesisDetail.term_set``, so a produce/edit round-trip can't persist it (the ``matched_terms`` precedent).
         *     Carries NO number (#3): a tier label + a one-line reason.
         */
        TierRecommendation: {
            /** Term */
            term: string;
            recommended_tier: components["schemas"]["TermTier"];
            /** Reason */
            reason: string;
        };
        /** TriggerRefOut */
        TriggerRefOut: {
            /** Label */
            label: string;
            kind: components["schemas"]["Kind"];
            grade?: components["schemas"]["Grade"] | null;
            /** Ticker */
            ticker?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["ProvenanceOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "watching" | "not_yet" | "flip_only" | "starter_entry" | "core_entry" | "managing";
        /**
         * WorkbenchScored
         * @description The Workbench scored read for a thesis: its value-chain segments + the scored members (the UI groups
         *     by `member.segment`). Re-derived on read — never persisted.
         */
        WorkbenchScored: {
            /**
             * Thesis Id
             * Format: uuid
             */
            thesis_id: string;
            /**
             * Asof
             * Format: date
             */
            asof: string;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["Segment"][];
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["ScoredMemberOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_theses_theses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisSummary"][];
                };
            };
        };
    };
    get_thesis_theses__thesis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_theses__thesis_id__call_get: {
        parameters: {
            query: {
                /** @description as-of date; the call uses no data knowable after it */
                asof: string;
            };
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scored_workbench_theses__thesis_id__scored_get: {
        parameters: {
            query: {
                /** @description as-of date; the scores use no data knowable after it */
                asof: string;
            };
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbenchScored"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_securities_workbench_securities_get: {
        parameters: {
            query?: {
                /** @description ticker or name fragment; a discovery net over the master */
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityMatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_scoring_facts_workbench_securities__security_id__extract_get: {
        parameters: {
            query?: {
                /** @description if given, propose a GROUNDED purity % for this thesis (SURFACE 1b); purity-only */
                thesis_id?: string | null;
            };
            header?: never;
            path: {
                security_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedFact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_flag_candidate_workbench_facts_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractedFact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_workbench_theses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteThesisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    produce_terms_workbench_theses__thesis_id__terms_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProduceTermsRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_terms_workbench_theses__thesis_id__terms_edit_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTermsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_tiers_endpoint_workbench_theses__thesis_id__recommend_tiers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierRecommendation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_draft_chain_workbench_theses__thesis_id__draft_chain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftJobRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_chain_job_workbench_theses__thesis_id__draft_chain_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_runs_workbench_theses__thesis_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saved_run_workbench_theses__thesis_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ratify_fact_workbench_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatifyRevenueMix"] | components["schemas"]["RatifyShares"] | components["schemas"]["RatifyCashBurn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatifiedFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
